//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HO.Apps.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HO.Apps.Localization.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver Order.
        /// </summary>
        internal static string Customer_Order_Detail_Deliver_Order {
            get {
                return ResourceManager.GetString("Customer_Order_Detail_Deliver_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-Week Sales By Major Category.
        /// </summary>
        internal static string Customer_Sales_By_Category_Header {
            get {
                return ResourceManager.GetString("Customer_Sales_By_Category_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Customers_Detail_Address {
            get {
                return ResourceManager.GetString("Customers_Detail_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Customers_Detail_CallDialog_Accept {
            get {
                return ResourceManager.GetString("Customers_Detail_CallDialog_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Customers_Detail_CallDialog_Cancel {
            get {
                return ResourceManager.GetString("Customers_Detail_CallDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to call .
        /// </summary>
        internal static string Customers_Detail_CallDialog_Message {
            get {
                return ResourceManager.GetString("Customers_Detail_CallDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial a Number.
        /// </summary>
        internal static string Customers_Detail_CallDialog_Title {
            get {
                return ResourceManager.GetString("Customers_Detail_CallDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to leave the Xamarin CRM app and get directions?.
        /// </summary>
        internal static string Customers_Detail_MappingDirections_LeaveApplication {
            get {
                return ResourceManager.GetString("Customers_Detail_MappingDirections_LeaveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Leave.
        /// </summary>
        internal static string Customers_Detail_MappingDirections_LeaveApplication_Yes {
            get {
                return ResourceManager.GetString("Customers_Detail_MappingDirections_LeaveApplication_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customers_Detail_Tab_Title {
            get {
                return ResourceManager.GetString("Customers_Detail_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Orders.
        /// </summary>
        internal static string Customers_OrderClosed {
            get {
                return ResourceManager.GetString("Customers_OrderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Orders.
        /// </summary>
        internal static string Customers_OrderOpen {
            get {
                return ResourceManager.GetString("Customers_OrderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Customers.
        /// </summary>
        internal static string Customers_Orders_CustomerTabbedPage_BackToCustomers {
            get {
                return ResourceManager.GetString("Customers_Orders_CustomerTabbedPage_BackToCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Order.
        /// </summary>
        internal static string Customers_Orders_EditOrder_AddToOrder {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_AddToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Customers_Orders_EditOrder_BackButton {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string Customers_Orders_EditOrder_ClosedDateTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ClosedDateTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Customers_Orders_EditOrder_CompanyTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Deliver.
        /// </summary>
        internal static string Customers_Orders_EditOrder_DeliverConfirmAffirmative {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DeliverConfirmAffirmative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivering will finalize this order and prevent future changes. This cannot be undone. Would you like to deliver this order?.
        /// </summary>
        internal static string Customers_Orders_EditOrder_DeliverConfirmDescription {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DeliverConfirmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver?.
        /// </summary>
        internal static string Customers_Orders_EditOrder_DeliverConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DeliverConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date.
        /// </summary>
        internal static string Customers_Orders_EditOrder_DueDateEntryPlaceholder {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DueDateEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        internal static string Customers_Orders_EditOrder_DueDateTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DueDateTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to exit and discard changes to this order?.
        /// </summary>
        internal static string Customers_Orders_EditOrder_ExitConfirmDescription {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ExitConfirmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit and Discard?.
        /// </summary>
        internal static string Customers_Orders_EditOrder_ExitConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ExitConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading product image....
        /// </summary>
        internal static string Customers_Orders_EditOrder_LoadingImageLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_LoadingImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        internal static string Customers_Orders_EditOrder_NewOrderTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_NewOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string Customers_Orders_EditOrder_OkayConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_OkayConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered.
        /// </summary>
        internal static string Customers_Orders_EditOrder_OrderDateTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_OrderDateTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order cannot be saved until a product is selected. Please select a product..
        /// </summary>
        internal static string Customers_Orders_EditOrder_OrderItemNotSelectedConfirmDescription {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_OrderItemNotSelectedConfirmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a product.
        /// </summary>
        internal static string Customers_Orders_EditOrder_OrderItemNotSelectedConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_OrderItemNotSelectedConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a price.
        /// </summary>
        internal static string Customers_Orders_EditOrder_PriceEntryPlaceholder {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_PriceEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Customers_Orders_EditOrder_PriceTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_PriceTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a product.
        /// </summary>
        internal static string Customers_Orders_EditOrder_ProductEntryPlaceholder {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ProductEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Customers_Orders_EditOrder_ProductTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ProductTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Customers_Orders_EditOrder_Save {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save changes to this order?.
        /// </summary>
        internal static string Customers_Orders_EditOrder_SaveConfirmDescription {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_SaveConfirmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        internal static string Customers_Orders_EditOrder_SaveConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_SaveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        internal static string Customers_Orders_NewOrder {
            get {
                return ResourceManager.GetString("Customers_Orders_NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Customers_Orders_Tab_Title {
            get {
                return ResourceManager.GetString("Customers_Orders_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Customers_Sales_Tab_Title {
            get {
                return ResourceManager.GetString("Customers_Sales_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit and Discard.
        /// </summary>
        internal static string Exit_and_Discard {
            get {
                return ResourceManager.GetString("Exit_and_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Directions.
        /// </summary>
        internal static string Get_Directions {
            get {
                return ResourceManager.GetString("Get_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lead.
        /// </summary>
        internal static string Leads_EditLead {
            get {
                return ResourceManager.GetString("Leads_EditLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to exit and discard changes to this lead?.
        /// </summary>
        internal static string Leads_ExitConfirmDescription {
            get {
                return ResourceManager.GetString("Leads_ExitConfirmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit and Discard?.
        /// </summary>
        internal static string Leads_ExitConfirmTitle {
            get {
                return ResourceManager.GetString("Leads_ExitConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Leads_LeadContactDetail_Address {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Leads_LeadContactDetail_City {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Leads_LeadContactDetail_Country {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Leads_LeadContactDetail_Email {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Leads_LeadContactDetail_FirstName {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Leads_LeadContactDetail_LastName {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Leads_LeadContactDetail_Phone {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string Leads_LeadContactDetail_PostalCode {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Leads_LeadContactDetail_Role {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Leads_LeadContactDetail_State {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Leads_LeadDetail_CompanyName {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Leads_LeadDetail_CompanyNamePlaceholder {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_CompanyNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        internal static string Leads_LeadDetail_Industry {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        internal static string Leads_LeadDetail_OpportunityHeading {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunityHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Leads_LeadDetail_OpportunitySize {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunitySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Dollar Amount.
        /// </summary>
        internal static string Leads_LeadDetail_OpportunitySizePlaceholder {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunitySizePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string Leads_LeadDetail_OpportunityStage {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunityStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Leads_LeadDetail_SaveButtonText {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads.
        /// </summary>
        internal static string Leads_LeadListHeaderTitle {
            get {
                return ResourceManager.GetString("Leads_LeadListHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Lead.
        /// </summary>
        internal static string Leads_NewLead {
            get {
                return ResourceManager.GetString("Leads_NewLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save changes to this lead?.
        /// </summary>
        internal static string Leads_SaveConfirmDescription {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        internal static string Leads_SaveConfirmTitle {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Application?.
        /// </summary>
        internal static string Leave_Application {
            get {
                return ResourceManager.GetString("Leave_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string NetworkConnection_Alert_Confirm {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires access to remote data, but you don&apos;t seem to currently have a network connnection. Check your connection and try again..
        /// </summary>
        internal static string NetworkConnection_Alert_Message {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string NetworkConnection_Alert_Title {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string NoPosition_Alert_Confirm {
            get {
                return ResourceManager.GetString("NoPosition_Alert_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find GPS coordinates for address.
        /// </summary>
        internal static string NoPosition_Alert_Message {
            get {
                return ResourceManager.GetString("NoPosition_Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Not Found.
        /// </summary>
        internal static string NoPosition_Alert_Title {
            get {
                return ResourceManager.GetString("NoPosition_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Page_AboutTitle {
            get {
                return ResourceManager.GetString("Page_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add m.i.l.k. Digital ID.
        /// </summary>
        internal static string Page_AddmilkDigitalID {
            get {
                return ResourceManager.GetString("Page_AddmilkDigitalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Page_HomeTitle {
            get {
                return ResourceManager.GetString("Page_HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.i.l.k. Digital Id.
        /// </summary>
        internal static string Page_milkDigitalID {
            get {
                return ResourceManager.GetString("Page_milkDigitalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code.
        /// </summary>
        internal static string Page_PromoCode {
            get {
                return ResourceManager.GetString("Page_PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Page_SettingTitle {
            get {
                return ResourceManager.GetString("Page_SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading product categories....
        /// </summary>
        internal static string Products_CategoryList_LoadingLabel {
            get {
                return ResourceManager.GetString("Products_CategoryList_LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading products....
        /// </summary>
        internal static string Products_ProductList_LoadingLabel {
            get {
                return ResourceManager.GetString("Products_ProductList_LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading leads data....
        /// </summary>
        internal static string SalesDashboard_Leads_LoadingLabel {
            get {
                return ResourceManager.GetString("SalesDashboard_Leads_LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-Week Sales.
        /// </summary>
        internal static string SalesDashboard_SalesChart_Header_Title {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Average.
        /// </summary>
        internal static string SalesDashboard_SalesChart_Header_WeeklyAverageTitle {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_Header_WeeklyAverageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading sales data....
        /// </summary>
        internal static string SalesDashboard_SalesChart_LoadingLabel {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string SalesDashboard_SalesChart_PrimaryAxis_Title {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_PrimaryAxis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Total.
        /// </summary>
        internal static string SalesDashboard_SalesChart_YAxis_Title {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_YAxis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Splash_PasswordTitleLabel {
            get {
                return ResourceManager.GetString("Splash_PasswordTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Promo Code.
        /// </summary>
        internal static string Splash_PromoCodeEntryPlaceholder {
            get {
                return ResourceManager.GetString("Splash_PromoCodeEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code.
        /// </summary>
        internal static string Splash_PromoCodeTitleLabel {
            get {
                return ResourceManager.GetString("Splash_PromoCodeTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string Splash_SignIn {
            get {
                return ResourceManager.GetString("Splash_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIP SIGN IN (demo).
        /// </summary>
        internal static string Splash_SkipSignIn {
            get {
                return ResourceManager.GetString("Splash_SkipSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.i.l.k. Digital ID.
        /// </summary>
        internal static string Splash_Title {
            get {
                return ResourceManager.GetString("Splash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Splash_UsernameTitleLabel {
            get {
                return ResourceManager.GetString("Splash_UsernameTitleLabel", resourceCulture);
            }
        }
    }
}
